#!/bin/bash

set -e
case "$1" in
    configure)
	echo "Post Installation configuration...."
#Script to create symbolic links for shared libraries
	ARCH=`arch`
	LIB_DIR="/usr/lib/"
	if [ "$ARCH" = "x86_64" ]; then
		BaseLib=("libnetsnmp.so.*")
		Snmp_Lib=("libnetsnmp.so.30")
	else
		BaseLib=("libnetsnmp.so.*" "libsnmp.so.*")
		Snmp_Lib=("libnetsnmp.so.15" "libsnmp.so.15")
	fi

        for((idx=0;idx<${#Snmp_Lib[@]};idx++)); do
        
                CUR_BASE_LIB=`find $LIB_DIR -name ${BaseLib[$idx]} -type f`
                
                if [ "$CUR_BASE_LIB" != "" ] ; then
                
                        LIB_PATH=`dirname $CUR_BASE_LIB`
                        LIB_PATH="$LIB_PATH/"
                        
                        Check_SnmpLib=`find $LIB_PATH -name ${Snmp_Lib[$idx]}`
                        
                        if [ "$Check_SnmpLib" = "" ] ; then
                        
                                ln -s `basename $CUR_BASE_LIB` $LIB_PATH${Snmp_Lib[$idx]}
                                
                        fi
                fi
        done

	;;
    *)
	exit 0
	;;
esac
exit 0
#DEBHELPER#
